version: '3'

services:

  mongo:
    image: mongo:4.4.18
    container_name: mongodb
    restart: unless-stopped
    tty: true
    volumes:
      - /opt/db/mongodb:/data/base

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
  
  chrome1:
    image: selenium/standalone-chrome:latest
    hostname: chrome1
    privileged: true
    shm_size: 2g

  chrome2:
    image: selenium/standalone-chrome:latest
    hostname: chrome2
    privileged: true
    shm_size: 2g

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api
    container_name: api
    restart: always
    tty: True
    working_dir: /api
    ports:
      - 4002:4002