version: '3'

services:

  chrome1:
    image: selenium/standalone-chrome:latest
    hostname: chrome1
    privileged: true
    shm_size: 2g

  chrome2:
    image: selenium/standalone-chrome:latest
    hostname: chrome2
    privileged: true
    shm_size: 2g

  balancer:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api
    container_name: api
    env_file:
      - api/.env
    restart: always
    tty: True
    working_dir: /api
    ports:
      - 8000:8000